services:
  app:
    image: ghcr.io/davenury/pf-gm-secret-rolls:v1.0.0
    container_name: pf-rolls

    ports:
      - "8080:8080"

    volumes:
      # Persist the backend repository/database on the host
      - ./back/repository/db:/app/back/repository/db

    restart: unless-stopped